<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "skitourenroutenlist"
 *
 * Auto generated by Extension Builder 2019-11-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Skitouren-Routen-List',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Hubertus Golf, Markus Stadler',
    'author_email' => 'info@berti-golf.de, mail@stadler-markus.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '11.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
